name: Validate Token Lists

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'src/tokens/**/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Validate token lists
      run: |
        for file in src/tokens/*.json; do
          echo "Validating $file..."
          bun run src/index.ts "$file"
        done
